<html>
<head><meta charset="utf-8"><title>[isabelle] Interrupt_Breakdown exception for function (do... · Mirror: Isabelle Users Mailing List · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/index.html">Mirror: Isabelle Users Mailing List</a></h2>
<h3>Topic: <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html">[isabelle] Interrupt_Breakdown exception for function (do...</a></h3>

<hr>

<base href="https://isabelle.zulipchat.com/">

<head><link href="http://isabelle.systems/zulip-archive/style.css" rel="stylesheet"></head>

<a name="483703143"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Interrupt_Breakdown%20exception%20for%20function%20%28do.../near/483703143" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html#483703143">(Nov 21 2024 at 13:58)</a>:</h4>
<p>From: Sarah Tilscher &lt;<a href="mailto:sarah.tilscher@tum.de">sarah.tilscher@tum.de</a>&gt;<br>
Dear isabelle developers,</p>
<p>When defining a fixpoint algorithm using the function package and its <br>
domintros option, I get an Interrupt_Breakdown exception already after <br>
proving the pattern completeness. I extracted the following small (but <br>
not anymore meaningful) example:</p>
<p>theory Scratch<br>
   imports Main<br>
begin</p>
<p>definition lookup_default :: "('x, nat) map ⇒ 'x ⇒ nat" where<br>
   "lookup_default σ x ≡ case σ x of Some v ⇒ v | None ⇒ 0"</p>
<p>function (domintros)<br>
   iterate :: "'x ⇒ ('x, nat) map ⇒ nat"<br>
      where<br>
   "iterate x σ = (<br>
     let d_new = lookup_default σ x in<br>
     if lookup_default σ x = d_new then<br>
       iterate x (σ(x ↦ lookup_default σ x))<br>
     else 0)"<br>
    apply auto<br>
   done (* Interrupt_Breakdown exception thrown *)</p>
<p>end</p>
<p>Does someone know why/where this exception is thrown? Any idea how to <br>
fix or circumvent this?</p>
<p>Thanks,<br>
Sarah</p>



<a name="483711791"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Interrupt_Breakdown%20exception%20for%20function%20%28do.../near/483711791" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html#483711791">(Nov 21 2024 at 14:32)</a>:</h4>
<p>From: Kevin Kappelmann &lt;<a href="mailto:kevin.kappelmann@tum.de">kevin.kappelmann@tum.de</a>&gt;<br>
I have no idea, but here is a shorter example:</p>
<div class="codehilite" data-code-language="Isabelle"><pre><span></span><code><span class="kn">function</span><span class="w"> </span><span class="o">(</span><span class="n">domintros</span><span class="o">)</span><span class="w"> </span><span class="n">f</span><span class="w"> </span><span class="o">::</span><span class="w"> </span><span class="s">"'a ⇒ 'a"</span><span class="w"> </span><span class="kp">where</span>
<span class="w">   </span><span class="s">"f x = (let x' = x in if x = x' then f x else x)"</span>
<span class="w">    </span><span class="kp">apply</span><span class="w"> </span><span class="n">auto</span>
<span class="w">    </span><span class="k">done</span>
</code></pre></div>
<p>On 21.11.24 14:50, Sarah Tilscher wrote:</p>
<blockquote>
<p>Dear isabelle developers,</p>
<p>When defining a fixpoint algorithm using the function package and its <br>
domintros option, I get an Interrupt_Breakdown exception already after <br>
proving the pattern completeness. I extracted the following small (but <br>
not anymore meaningful) example:</p>
<p>theory Scratch<br>
   imports Main<br>
begin</p>
<p>definition lookup_default :: "('x, nat) map ⇒ 'x ⇒ nat" where<br>
   "lookup_default σ x ≡ case σ x of Some v ⇒ v | None ⇒ 0"</p>
<p>function (domintros)<br>
   iterate :: "'x ⇒ ('x, nat) map ⇒ nat"<br>
      where<br>
   "iterate x σ = (<br>
     let d_new = lookup_default σ x in<br>
     if lookup_default σ x = d_new then<br>
       iterate x (σ(x ↦ lookup_default σ x))<br>
     else 0)"<br>
    apply auto<br>
   done (* Interrupt_Breakdown exception thrown *)</p>
<p>end</p>
<p>Does someone know why/where this exception is thrown? Any idea how to <br>
fix or circumvent this?</p>
<p>Thanks,<br>
Sarah</p>
</blockquote>



<a name="483712003"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Interrupt_Breakdown%20exception%20for%20function%20%28do.../near/483712003" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html#483712003">(Nov 21 2024 at 14:33)</a>:</h4>
<p>From: Tobias Nipkow &lt;<a href="mailto:nipkow@in.tum.de">nipkow@in.tum.de</a>&gt;<br>
Hi Sarah,</p>
<p>It it looks like something in the function definition command does not terminate <br>
(and is forcefully terminated by the system, I suspect). Of course that <br>
shouldn't happen. This particular example can be fixed by expanding the "let". <br>
(you can always recover the original version later on as a lemma).</p>
<p>Tobias</p>
<p>On 21/11/2024 14:50, Sarah Tilscher wrote:</p>
<blockquote>
<p>Dear isabelle developers,</p>
<p>When defining a fixpoint algorithm using the function package and its domintros <br>
option, I get an Interrupt_Breakdown exception already after proving the pattern <br>
completeness. I extracted the following small (but not anymore meaningful) example:</p>
<p>theory Scratch<br>
   imports Main<br>
begin</p>
<p>definition lookup_default :: "('x, nat) map ⇒ 'x ⇒ nat" where<br>
   "lookup_default σ x ≡ case σ x of Some v ⇒ v | None ⇒ 0"</p>
<p>function (domintros)<br>
   iterate :: "'x ⇒ ('x, nat) map ⇒ nat"<br>
      where<br>
   "iterate x σ = (<br>
     let d_new = lookup_default σ x in<br>
     if lookup_default σ x = d_new then<br>
       iterate x (σ(x ↦ lookup_default σ x))<br>
     else 0)"<br>
    apply auto<br>
   done (* Interrupt_Breakdown exception thrown *)</p>
<p>end</p>
<p>Does someone know why/where this exception is thrown? Any idea how to fix or <br>
circumvent this?</p>
<p>Thanks,<br>
Sarah</p>
</blockquote>
<p><a href="/user_uploads/14278/HjmI1v6r7hwcBpY-T2r6-HAG/smime.p7s">smime.p7s</a></p>



<a name="483714653"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Interrupt_Breakdown%20exception%20for%20function%20%28do.../near/483714653" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html#483714653">(Nov 21 2024 at 14:45)</a>:</h4>
<p>From: <a href="mailto:mohammad.abdulaziz8@gmail.com">mohammad.abdulaziz8@gmail.com</a><br>
Having an equation and its flipped version causes the simplifier to not <br>
terminate. The following works:</p>
<div class="codehilite" data-code-language="Isabelle"><pre><span></span><code><span class="kn">function</span><span class="w"> </span><span class="o">(</span><span class="n">domintros</span><span class="o">)</span><span class="w"> </span><span class="n">f</span><span class="w"> </span><span class="o">::</span><span class="w"> </span><span class="s">"'a ⇒ 'a"</span><span class="w"> </span><span class="kp">where</span>
<span class="w">    </span><span class="s">"f x = (let x' = x in if x' = x then f x else x)"</span>
<span class="w">   </span><span class="k">by</span><span class="w"> </span><span class="o">(</span><span class="n">pat_completeness</span><span class="o">)</span><span class="w"> </span><span class="n">auto</span>
</code></pre></div>
<p>Mohammad</p>
<p>On 21/11/2024 14:27, Kevin Kappelmann wrote:</p>
<blockquote>
<p>I have no idea, but here is a shorter example:</p>
<p><code>
function (domintros) f :: "'a ⇒ 'a" where
   "f x = (let x' = x in if x = x' then f x else x)"
    apply auto
    done
</code></p>
<p>On 21.11.24 14:50, Sarah Tilscher wrote:</p>
<blockquote>
<p>Dear isabelle developers,</p>
<p>When defining a fixpoint algorithm using the function package and its <br>
domintros option, I get an Interrupt_Breakdown exception already after <br>
proving the pattern completeness. I extracted the following small (but <br>
not anymore meaningful) example:</p>
<p>theory Scratch<br>
   imports Main<br>
begin</p>
<p>definition lookup_default :: "('x, nat) map ⇒ 'x ⇒ nat" where<br>
   "lookup_default σ x ≡ case σ x of Some v ⇒ v | None ⇒ 0"</p>
<p>function (domintros)<br>
   iterate :: "'x ⇒ ('x, nat) map ⇒ nat"<br>
      where<br>
   "iterate x σ = (<br>
     let d_new = lookup_default σ x in<br>
     if lookup_default σ x = d_new then<br>
       iterate x (σ(x ↦ lookup_default σ x))<br>
     else 0)"<br>
    apply auto<br>
   done (* Interrupt_Breakdown exception thrown *)</p>
<p>end</p>
<p>Does someone know why/where this exception is thrown? Any idea how to <br>
fix or circumvent this?</p>
<p>Thanks,<br>
Sarah</p>
</blockquote>
</blockquote>



<a name="483716182"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/247541-Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Interrupt_Breakdown%20exception%20for%20function%20%28do.../near/483716182" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/247541-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Interrupt_Breakdown.20exception.20for.20function.20.28do.2E.2E.2E.html#483716182">(Nov 21 2024 at 14:52)</a>:</h4>
<p>From: Sarah Tilscher &lt;<a href="mailto:sarah.tilscher@tum.de">sarah.tilscher@tum.de</a>&gt;<br>
Thank you for looking into this! I also just found out, that flipping <br>
the condition in the if-statement avoids the problem. This also works <br>
for my original definition. Inlining the let-definition is a bit more <br>
cumbersome, because it is used in several places.</p>
<p>Sarah</p>
<p>On 21.11.24 15:45, <a href="mailto:mohammad.abdulaziz8@gmail.com">mohammad.abdulaziz8@gmail.com</a> wrote:</p>
<blockquote>
<p>Having an equation and its flipped version causes the simplifier to not <br>
terminate. The following works:</p>
<p><code>
function (domintros) f :: "'a ⇒ 'a" where
    "f x = (let x' = x in if x' = x then f x else x)"
   by (pat_completeness) auto
</code></p>
<p>Mohammad</p>
<p>On 21/11/2024 14:27, Kevin Kappelmann wrote:</p>
<blockquote>
<p>I have no idea, but here is a shorter example:</p>
<p><code>
function (domintros) f :: "'a ⇒ 'a" where
   "f x = (let x' = x in if x = x' then f x else x)"
    apply auto
    done
</code></p>
<p>On 21.11.24 14:50, Sarah Tilscher wrote:</p>
<blockquote>
<p>Dear isabelle developers,</p>
<p>When defining a fixpoint algorithm using the function package and its <br>
domintros option, I get an Interrupt_Breakdown exception already <br>
after proving the pattern completeness. I extracted the following <br>
small (but not anymore meaningful) example:</p>
<p>theory Scratch<br>
   imports Main<br>
begin</p>
<p>definition lookup_default :: "('x, nat) map ⇒ 'x ⇒ nat" where<br>
   "lookup_default σ x ≡ case σ x of Some v ⇒ v | None ⇒ 0"</p>
<p>function (domintros)<br>
   iterate :: "'x ⇒ ('x, nat) map ⇒ nat"<br>
      where<br>
   "iterate x σ = (<br>
     let d_new = lookup_default σ x in<br>
     if lookup_default σ x = d_new then<br>
       iterate x (σ(x ↦ lookup_default σ x))<br>
     else 0)"<br>
    apply auto<br>
   done (* Interrupt_Breakdown exception thrown *)</p>
<p>end</p>
<p>Does someone know why/where this exception is thrown? Any idea how to <br>
fix or circumvent this?</p>
<p>Thanks,<br>
Sarah</p>
</blockquote>
</blockquote>
</blockquote>



<hr><p>Last updated: Nov 01 2025 at 16:22 UTC</p>
</html>