[
    {
        "content": "<p>From: \"Eugene W. Stark\" &lt;<a href=\"mailto:isabelle-users@starkeffect.com\">isabelle-users@starkeffect.com</a>&gt;<br>\nHere is an example of the external prover (in this case, cvc4) crash situation, which just occurred during<br>\nmy current session.  I include just the text output from the core dump in /var/crash, which shows the SIGABRT:</p>",
        "id": 353236030,
        "sender_full_name": "Email Gateway",
        "timestamp": 1682594519
    },
    {
        "content": "<p>From: Makarius &lt;<a href=\"mailto:makarius@sketis.net\">makarius@sketis.net</a>&gt;<br>\nI don't see anything specific here, probably just a spurious crash of cvc4-1.8.</p>\n<p>This looks unrelated to questions about Isabelle/ML and Isabelle/Scala <br>\nmanagement of tasks, threads, processes.</p>\n<p>It does remind me that we wanted to move forward to a more recent version, but <br>\ndidn't for some other reasons.</p>\n<p>Makarius</p>",
        "id": 353263827,
        "sender_full_name": "Email Gateway",
        "timestamp": 1682598170
    },
    {
        "content": "<p>From: Jasmin Blanchette &lt;<a href=\"mailto:jasmin.blanchette@ifi.lmu.de\">jasmin.blanchette@ifi.lmu.de</a>&gt;<br>\nActually, the reason we didn't move forward to cvc5 is that cvc5 crashed very often on my Intel Mac. Maybe the issue doesn't arise with other platforms and we can soon move to cvc5.</p>\n<p>Jasmin</p>",
        "id": 353266357,
        "sender_full_name": "Email Gateway",
        "timestamp": 1682598497
    },
    {
        "content": "<p>From: Makarius &lt;<a href=\"mailto:makarius@sketis.net\">makarius@sketis.net</a>&gt;<br>\nHopefully, yes.</p>\n<p>Note that I've seen quite a lot of crashes recently on the older Intel Mac <br>\nMini test machines that I happen to have access to.</p>\n<p>Maybe the hardware is just degrading, or the OS versions. Or maybe some <br>\n\"planned obsolescence\" by Apple to get rid of the Intel platform.</p>\n<p>Makarius</p>",
        "id": 353285769,
        "sender_full_name": "Email Gateway",
        "timestamp": 1682601011
    },
    {
        "content": "<p>From: \"Eugene W. Stark\" &lt;<a href=\"mailto:isabelle-users@starkeffect.com\">isabelle-users@starkeffect.com</a>&gt;<br>\nI don't see this as \"just a spurious crash of cvs4-1.8\".  I would expect a \"spurious crash\" to be something<br>\nlike receiving SIGSEGV as a result of a null pointer exception, for example.  However, in this case the signal<br>\nreceived is SIGABRT, as can be verified from the following line of the dump:</p>\n<blockquote>\n<p>Signal: 6</p>\n</blockquote>\n<p>Moreover, an unusual feature is that the process itself is in the sleep state when this occurs, as can be<br>\nverified by the following lines:</p>\n<blockquote>\n<p>ProcStatus:<br>\n Name:  cvc4<br>\n Umask: 0002<br>\n State: S (sleeping)</p>\n</blockquote>\n<p>Now, the fact that the process is sleeping would seem to indicate that the SIGABRT was not a signal that was<br>\ngenerated by the process itself, but rather was sent to the process by another process.  I do not think it<br>\nis possible for a process in the sleeping state to cause a signal to be sent to itself.  This implies that<br>\nthe abnormal termination was <em>not</em> the synchronous result of some erroneous action taken by the program that<br>\ncaused the SIGABRT, nor even the result of an assertion in the program whose failure might have caused SIGABRT.</p>\n<p>My recollection from my previous investigation into this issue is that SIGABRT is the signal that is sent<br>\nfrom the Isabelle system (Isabelle/Scala?) to cause an external prover to terminate when its results are<br>\nno longer required.  Normally, the prover would have a handler installed for SIGABRT, it would catch this<br>\nsignal and arrange to terminate gracefully.  Indeed, that is apparently what happens most of the time.<br>\nHowever, sometimes it seems that SIGABRT arrives when there is not a handler installed to catch it.<br>\nIn that case it causes the external prover to terminate with a core dump, which is flagged by the kernel<br>\nand which is what causes the pop-up notification and the dump file to be created in /var/crash.</p>\n<p>In my previous investigation I do not recall being able to determine why the SIGABRT would arrive sometimes<br>\nwhen there was no handler for it.  But, again, I do not think the behavior recorded here should be<br>\ndismissed as \"just a spurious crash\".</p>\n<p>- Gene Stark</p>\n<p>On 4/27/23 08:22, Makarius wrote:</p>\n<blockquote>\n<p>On 27/04/2023 13:21, Eugene W. Stark wrote:</p>\n<blockquote>\n<p>Here is an example of the external prover (in this case, cvc4) crash situation, which just occurred during<br>\nmy current session.Â  I include just the text output from the core dump in /var/crash, which shows the SIGABRT:</p>\n<blockquote>\n<p>ProblemType: Crash<br>\nArchitecture: amd64<br>\nCrashCounter: 1<br>\nCurrentDesktop: GNOME<br>\nDate: Tue Apr 18 12:09:48 2023<br>\nDistroRelease: Ubuntu 22.04<br>\nExecutablePath: /opt/Isabelle2022/contrib/cvc4-1.8/x86_64-linux/cvc4</p>\n</blockquote>\n</blockquote>\n<p>I don't see anything specific here, probably just a spurious crash of cvc4-1.8.</p>\n<p>This looks unrelated to questions about Isabelle/ML and Isabelle/Scala management of tasks, threads, processes.</p>\n<p>It does remind me that we wanted to move forward to a more recent version, but didn't for some other reasons.</p>\n<p>Makarius</p>\n</blockquote>",
        "id": 353495278,
        "sender_full_name": "Email Gateway",
        "timestamp": 1682630088
    }
]