<html>
<head><meta charset="utf-8"><title>[isabelle] Handling failed proof · Archive Mirror: Isabelle Users Mailing List · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/index.html">Archive Mirror: Isabelle Users Mailing List</a></h2>
<h3>Topic: <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html">[isabelle] Handling failed proof</a></h3>

<hr>

<base href="https://isabelle.zulipchat.com/">

<head><link href="http://isabelle.systems/zulip-archive/style.css" rel="stylesheet"></head>

<a name="294116135"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/336180-Archive%20Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Handling%20failed%20proof/near/294116135" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html#294116135">(Aug 18 2022 at 15:59)</a>:</h4>
<p>From: John Munroe &lt;<a href="mailto:munddr@gmail.com">munddr@gmail.com</a>&gt;<br>
Hi,</p>
<p>I'm wondering why the exception handling in the following doesn't<br>
behave what I expected to. Does it not try to prove goal1, and if it<br>
fails, it tries to prove goal2? goal2 should be provable, but I still<br>
get a Proof failed exception.</p>
<p>let<br>
  val ctxt = @{context}<br>
  val goal1 = @{prop "EX x y. x &gt; y"}<br>
  val goal2 = @{prop "EX (x::real) y. x &gt; y"}<br>
in<br>
  Goal.prove ctxt [] [] goal1<br>
   (fn _ =&gt; auto_tac (clasimpset_of ctxt))<br>
   handle THM _ =&gt;<br>
  Goal.prove ctxt [] [] goal2<br>
   (fn _ =&gt; auto_tac (clasimpset_of ctxt))<br>
end;</p>
<p>Thank you for the help.</p>
<p>John</p>



<a name="294116150"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/336180-Archive%20Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Handling%20failed%20proof/near/294116150" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html#294116150">(Aug 18 2022 at 15:59)</a>:</h4>
<p>From: Makarius &lt;<a href="mailto:makarius@sketis.net">makarius@sketis.net</a>&gt;<br>
The exception produced by Goal.prove is ERROR, not THM (which is a for <br>
operations close to the inference kernel).</p>
<p>Normally you would organize proof attempts using tacticals such as ORELSE, <br>
within a single goal state configuration.</p>
<p>Makarius</p>



<a name="294116161"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/336180-Archive%20Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Handling%20failed%20proof/near/294116161" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html#294116161">(Aug 18 2022 at 15:59)</a>:</h4>
<p>From: Alexander Krauss &lt;<a href="mailto:krauss@in.tum.de">krauss@in.tum.de</a>&gt;<br>
John Munroe wrote:<br>
[...]</p>
<p>The Goal module catches the internal THM exception itself and re-raises <br>
it as a user error (exception ERROR). So the "handle THM _" does not <br>
catch it...</p>
<p>Alex</p>



<a name="294116215"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/336180-Archive%20Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Handling%20failed%20proof/near/294116215" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html#294116215">(Aug 18 2022 at 15:59)</a>:</h4>
<p>From: Jeremy Dawson &lt;<a href="mailto:jeremy@rsise.anu.edu.au">jeremy@rsise.anu.edu.au</a>&gt;<br>
John Munroe wrote:<br>
John,</p>
<p>Without addressing your specific example closely,  I can just point out <br>
that to talk of a tactic application "failing" (as the documentation <br>
does) is potentially ambiguous.</p>
<p>It  can mean<br>
(1) the resulting lazy list of new proof states is empty<br>
(2) an ML exception is raised</p>
<p>Needless to say one sort of failure can (and no doubt there are examples <br>
in the code) can be converted to the other</p>
<p>I'd guess that this issue would explain the unexpected behaviour</p>
<p>Jeremy</p>



<a name="294116283"></a>
<h4><a href="https://isabelle.zulipchat.com/#narrow/stream/336180-Archive%20Mirror%3A%20Isabelle%20Users%20Mailing%20List/topic/%5Bisabelle%5D%20Handling%20failed%20proof/near/294116283" class="zl"><img src="http://isabelle.systems/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Email Gateway <a href="http://isabelle.systems/zulip-archive/stream/336180-Archive-Mirror.3A-Isabelle-Users-Mailing-List/topic/.5Bisabelle.5D.20Handling.20failed.20proof.html#294116283">(Aug 18 2022 at 16:00)</a>:</h4>
<p>From: John Munroe &lt;<a href="mailto:munddr@gmail.com">munddr@gmail.com</a>&gt;</p>
<blockquote>
<p>Without addressing your specific example closely,  I can just point out that<br>
to talk of a tactic application "failing" (as the documentation does) is<br>
potentially ambiguous.</p>
<p>It  can mean<br>
(1) the resulting lazy list of new proof states is empty<br>
(2) an ML exception is raised</p>
<p>Needless to say one sort of failure can (and no doubt there are examples in<br>
the code) can be converted to the other</p>
<p>I'd guess that this issue would explain the unexpected behaviour<br>
</p>
</blockquote>
<p>Handling ERROR instead solves my problem. Thanks!</p>
<p>John</p>
<blockquote>
<p>Jeremy</p>
</blockquote>



<hr><p>Last updated: Nov 01 2025 at 16:22 UTC</p>
</html>