[
    {
        "content": "<p>From: José Manuel Rodríguez Caballero &lt;<a href=\"mailto:josephcmac@gmail.com\">josephcmac@gmail.com</a>&gt;<br>\nHello,<br>\n  I do not know whether this is important to report this or not, but I was<br>\nusing Isabelle2019 and I received the following error message while<br>\ninvoking Sledgehammer:</p>\n<p>\"z3\": A prover error occurred:<br>\nexception Fail raised (line 222 of \"~~/src/HOL/Tools/SMT/z3_proof.ML\"):<br>\nReplaying the proof trace produced by Z3 failed: the bound \"?0\" is<br>\nundeclared; this indicates a bug in Z3</p>\n<p>I hope that this information may be helpful in the development of<br>\nIsabelle2019.</p>\n<p>Kind Regards,<br>\nJosé M.</p>",
        "id": 294753758,
        "sender_full_name": "Email Gateway",
        "timestamp": 1661196485
    },
    {
        "content": "<p>From: Makarius &lt;<a href=\"mailto:makarius@sketis.net\">makarius@sketis.net</a>&gt;<br>\nCan you also provide the example that produced this error? Does this<br>\nalso happen in Isabelle2018? What is your OS platform?</p>\n<p>Makarius</p>",
        "id": 294753770,
        "sender_full_name": "Email Gateway",
        "timestamp": 1661196492
    }
]