[
    {
        "content": "<p>From: Rafal Kolanski &lt;<a href=\"mailto:rafalk@cse.unsw.edu.au\">rafalk@cse.unsw.edu.au</a>&gt;<br>\nDear Isabelle Users,</p>\n<p>I'd like to ask you about an issue I have with Proof General (CVS <br>\nversion) and see if someone has a quick work-around of any kind.</p>\n<p>I've already filed a bug report, but as it's the only PG activity in the <br>\nlast 90+ days, I don't know if anyone will get around to looking at it:<br>\n<a href=\"http://proofgeneral.inf.ed.ac.uk/trac/ticket/322\">http://proofgeneral.inf.ed.ac.uk/trac/ticket/322</a></p>\n<p>Basically, attempting to use the \"tracing\" function inside ML makes PG <br>\nchoke, at least when it is done inside a proof method (which I use for <br>\ndebugging when writing a new proof method). Here is an example:</p>\n<p>theory SC imports Main<br>\nbegin</p>\n<p>ML {*<br>\n   fun moo_tac ctxt (ct,i) = (<br>\n       tracing (\"Target: MOO!\");<br>\n       no_tac);<br>\n*}</p>\n<p>method_setup moo = {*<br>\n   Scan.succeed (fn ctxt =&gt;<br>\n     SIMPLE_METHOD' (CSUBGOAL (moo_tac ctxt)))<br>\n*} \"Some proof method reduced to a simple thing which fails.\"</p>\n<p>(* don't match on different state vars *)<br>\nlemma \"X ==&gt; Y\"<br>\n   apply (moo)</p>\n<p>At this point, PG stops with:</p>\n<p>error in process filter: proof-shell-process-urgent-message: Wrong <br>\nnumber of arguments: #[(str) [...] [proof-trace-buffer str newline] 1 <br>\n(\"/home/rafalk/repos/l4.verified/isabelle/contrib/ProofGeneral/generic/pg-response.elc\" <br>\n. 12897)], 3</p>\n<p>The [...] includes non-printable characters, hence omitted.</p>\n<p>Has anyone seen anything similar?</p>\n<p>Sincerely,</p>\n<p>Rafal Kolanski.</p>",
        "id": 294104596,
        "sender_full_name": "Email Gateway",
        "timestamp": 1660834816
    }
]